### PR TITLE
Minecraft 1.20.4 support.

### PR DESCRIPTION
**Pull request by indaqoo**
Hi,

`WallMountLocation` was renamed to `BlockFace`.
This will fix the `/geodesy analyze` command issue with 1.20.4 versions.

### CODE REVIEW

**Comment by kosma** [comment]
Thank you ❤️ I will merge this soon, I need to take a good look at the version support situation.

**Comment by ruben2s** [comment]
Hi, any chance this is going to get published soon? Github actions seems to not have any build available to download regarding this change.

Thanks!

**Comment by indaqoo** [comment]
> Hi, any chance this is going to get published soon? Github actions seems to not have any build available to download regarding this change.
> 
> Thanks!

Hi @ruben2s,
I think you could clone this repo and build it yourself until @kosma has done all required version support checks, etc.

**Comment by kosma** [comment]
Fixed in 61b9264. Couple of notes:

1. The offending change wasn't the rename of WallMountLocation to BlockFace (that's a Yarn named rename, those are harmless), it was a hard to explain intermediary rename of Blocks.PUMPKIN from `field_10261` to `field_46282`. Go figure.
2. The change was done in 1.20.3 but the mod works on both .3 and .4 now.

**Pull request closed without merging**
